### PR TITLE
Clipped arrows of the logo

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by NullHypothesis** [comment]
Cool, thanks for the patch, Ivan! I like it, but could you also align the arrows so that they seem like an extension of the "x", like in the old logo? I think it would also look better if the lower arrow would go under the "p" instead of over it.

**Comment by mark-in** [comment]
@NullHypothesis, hmm. What do you mean by "old logo"? Before my changes? Binary output is still the same - I haven't changed logo itself. Arrows are already seem like an extension of "x", lower arrow does not go over "p". You want this arrow to be extended?

**Comment by NullHypothesis** [comment]
Oh, nevermind. I was misled by GitHub's image preview that falsely suggested that the image changed.

The patch looks good but would you mind deleting the second commit? I prefer to create a png version myself because I don't want to merge binary patches.

**Comment by NullHypothesis** [comment]
Closing since I just merged #50.

**Pull request closed without merging**
