### PR TITLE
Test Re-Organization

### PR DESCRIPTION
**Pull request by frankcash**
Moves the tests from `src/` to `test/`.
They were starting to clutter up `src/`.

I also extended test coverage by `3%` :high_brightness:!
I simply added coverage for some `None` type returns I didn't account for originally.

Works on https://github.com/NullHypothesis/exitmap/issues/22

### CODE REVIEW

**Comment by NullHypothesis** [comment]
Thanks for the pull request, Frank. Could you please also change the test code in .travis.yml?

**Comment by frankcash** [comment]
Sorry about that, will do!

**Comment by frankcash** [comment]
Looks like it passes all version except for 2.6.
It appears `assertIsNone` is [2.7+](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertIsNone)

**Comment by NullHypothesis** [comment]
(Sorry for the delay. Had to work on the weekend and I'm catching up now.)

I think it's sane to not support Python 2.6 anymore. Would you mind updating .travis.yml and removing the tests for 2.6?

**Comment by frankcash** [comment]
I updated the `.travis.yml`, don't think there is anything else that needs to be changed

**Comment by NullHypothesis** [comment]
Looks good, thanks for your help!

**Comment by frankcash** [comment]
Glad I could help :smile:

**Pull request merged**
