### PR TITLE
RFC: New module 'rtt' and a bunch of changes in aid of what it does

### PR DESCRIPTION
**Pull request by zackw**
This PR adds a new module `rtt.py`, which measures round-trip times through exits, and makes a bunch of improvements to the core in aid of what it does.  Please see individual commit messages for explanations.

I'm happy with the changes to the core.  However, please note that rtt.py is not yet fully reliable; I could use some debugging help.  It _starts out_ working well, but if you run it over lots of exits and destinations, more and more connections fail as time goes by, with errors like 

```
2016-03-27 10:23:42,862 [WARNING]: Failed to attach stream because: Unknown circuit "None"
```

and

```
  File ".../exitmap/src/modules/rtt.py", line 148, in perform_probes
    sock = socket.socket(AF_INET, SOCK_STREAM)
  File ".../exitmap/src/torsocks.py", line 343, in torsocket
    return _Torsocket(family, type, proto, _sock)
  File ".../exitmap/src/torsocks.py", line 114, in __init__
    self._authenticate()
  File ".../exitmap/src/torsocks.py", line 181, in _authenticate
    send_queue(self.getsockname())
  File ".../exitmap/src/torsocks.py", line 79, in send_queue
    queue.put([circ_id, sock_name])
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
```

### CODE REVIEW

**Comment by NullHypothesis** [comment]
These changes look great, thanks Zack! Would you mind running the `pep8` tool over your files? It analyses the code and points out lines that violate Python's PEP 8 style guide, which I'm trying to honour in exitmap.

Regarding your issue with `rtt.py`: I wonder if your module triggers some heuristic in Tor that makes it close these circuits. Have you tried starting exitmap in debug mode and looking at all circuit events that happen for a circuit before it causes this error message?

**Comment by zackw** [comment]
> Would you mind running the pep8 tool over your files? It analyses the code and points out lines that violate Python's PEP 8 style guide, which I'm trying to honour in exitmap.

This makes a large number of suggestions that IMHO harm readability.  The biggest problem is with code of the form

```
    exits = get_exits(args.data_dir,
                      country_code = args.countrycode,
                      bad_exit     = args.badexit,
                      good_exit    = args.goodexit,
                      version      = args.version,
                      nickname     = args.nickname,
                      address      = args.address)
```

It is only happy if I write

```
    exits = get_exits(args.data_dir,
                      country_code=args.countrycode,
                      bad_exit=args.badexit,
                      good_exit=args.goodexit,
                      version=args.version,
                      nickname=args.nickname,
                      address=args.address)
```

which I think is significantly less readable.  This occurs in a whole bunch of places, since there are many functions in this codebase that take lots of keyword arguments.  It is also insisting on the insertion of blank lines within in a block of stub methods, e.g.

```
    # These sockets can only be used as connected sockets.
    def sendto(self, *a): raise NotImplementedError
    def recvfrom(self, *a): raise NotImplementedError
    def recvfrom_into(self, *a): raise NotImplementedError
```

which would destroy the logical grouping.

Also, pep8 conformance changes to `selectors34.py` and `six.py` would be inappropriate, since they are imported verbatim from elsewhere.

I have made all of the pep8 changes that I think improve, or at least do no *harm*, to readability, and I also have a fix for one of the CI failures (not sure what's up with the other two) but before I revise the pull request I would like to know if you insist on pep8 conformance even in the above cases.

**Comment by zackw** [comment]
Note: having now actually _read_ PEP 8, it appears generally to endorse the principle that local readability is more important than complete conformance with the rules, and it specifically calls out "a bunch of related one-liners (e.g. a set of dummy implementations)" as not needing to have blank lines between them.

There's another interesting case I meant to mention: rtt.py has a set of configuration parameter variables as the first thing in the file after the module docstring, before the imports.  PEP 8 says the imports should be immediately after the docstring, but I don't want to do that because the import block is long and complicated (due to various compatibility hacks); I think people might not realize there _were_ "please edit these for your use case" variables if they were under the imports.  Instead I would like to see about getting module-specific command line arguments implemented so that people do not _need_ to edit the module, and then these can just go away.

**Comment by zackw** [comment]
Filed https://github.com/PyCQA/pycodestyle/issues/495 on the alignment issue.

**Comment by NullHypothesis** [comment]
Thanks again.

**Pull request merged**
